apiVersion: v1
kind: Service
metadata:
  name: {{ template "pdns.fullname" . }}-udp
  labels:
    app: {{ template "pdns.name" . }}
    chart: {{ template "pdns.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.serviceUdp.type }}
  {{- if .Values.serviceUdp.loadBalancerIP }}
  loadBalancerIP: {{ .Values.serviceUdp.loadBalancerIP }}
  {{- end }}
  ports:
    - port: 53
      targetPort: 53
      protocol: UDP
      name: dns-udp
  selector:
    app: {{ template "pdns.name" . }}
    release: {{ .Release.Name }}