apiVersion: v1
kind: Service
metadata:
  name: {{ template "pdns.fullname" . }}-tcp
  labels:
    app: {{ template "pdns.name" . }}
    chart: {{ template "pdns.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.serviceTcp.type }}
  {{- if .Values.serviceTcp.loadBalancerIP }}
  loadBalancerIP: {{ .Values.serviceTcp.loadBalancerIP }}
  {{- end }}
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
      name: api
    - port: 53
      targetPort: 53
      protocol: TCP
      name: dns-tcp
  selector:
    app: {{ template "pdns.name" . }}
    release: {{ .Release.Name }}
